### ISSUE TITLE
issues/task4.md

### ISSUE THREAD

**Issue by LareinaM** [csci3250-2019/project-team-c#11]

**Comment by LareinaM** [comment]
cannot flip the Travis CI, waiting for reply...

**Comment by 3words** [comment]
https://csci3250-2019.github.io/project-team-c/
your code has not work please fix it

**Comment by LareinaM** [comment]
@3words Because I cannot use Travis CI (I guess all groups cannot do so), still waiting for reply from Dr. CHAU.

**Comment by glorias1** [comment]
Wondering why it still doesn’t work🤔🤔

**Comment by LareinaM** [comment]
@glorias1 don't know neither, so weird
"undefined reference to `main'"??

**Comment by LareinaM** [comment]
found the problem
I hate merge thing

**Comment by LareinaM** [comment]
@glorias1 found the problem, I was sooo silly to let merge conflicts caught me again
plz review that pr?
This time it definitely works
