### ISSUE TITLE
My name and my friends is not on the course page

### ISSUE THREAD

**Issue by architkithania** [csci3250-2019/project-team-c#43]
My name and my friends is not there in the project main page and also our repo's README.md . Please tell me how to resolve this. Thanks.

**Comment by architkithania** [comment]
I believe the person who did Issue2 was supposed to include our name but accidentally forgot.

**Comment by glorias1** [comment]
Oh I saw your pull request, but I don’t know why Travis.ci(hope I spell correctly) crushes down. Errr @chuckjee plz help

**Comment by glorias1** [comment]
Seems like all pull requests cannot proceed due to the travis

**Comment by LareinaM** [comment]
@glorias1 someone changed the code.c incorrectly
so all requests fail
we need to fix that thing first, waiting for @AlbertngSeadragon

**Comment by architkithania** [comment]
we should create a new branch, fix the code there and the other should branch of that new branch.

**Comment by LareinaM** [comment]
yes the first thing is to fix the code, but that requires review of @AlbertngSeadragon ...
the other request must be done after fixing the code

**Comment by 3words** [comment]
> I believe the person who did Issue2 was supposed to include our name but accidentally forgot.

Please read task.md point number 8. You are required to add your name by yourself.

**Comment by AlbertngSeadragon** [comment]
oh really sorry guys, i want to try something accidentally crash it but dont know how to fixed it really sorry

**Comment by architkithania** [comment]
@3words yea sorry about that. I have resolved that
